package LibNet;

import PetriObj.ArcIn;
import PetriObj.ArcOut;
import PetriObj.ExceptionInvalidTimeDelay;
import PetriObj.PetriNet;
import PetriObj.PetriP;
import PetriObj.PetriT;
import java.util.ArrayList;

public class NetLibrary {

	/**
	 * Creates Petri net for taxi service
	 * @param operators number of operators in taxi service
	 * @param drivers number of drivers in taxi service
	 * @return created Petri net
     */
	public static PetriNet CreateNetModel(int operators, int drivers, double meanCallArrival, double meanPhoneNumberDialing, double meanTaxiOrdering, double meanWaitingForCalling, double meanServing) throws ExceptionInvalidTimeDelay {
		double[] distances = { 0, 5, 8, 9, 11, 12, 20 };
		double[] distanceProbabilities = { 0, 0.1, 0.3, 0.55, 0.72, 0.95, 1.0 };

		ArrayList<PetriP> d_P = new ArrayList<>();
		ArrayList<PetriT> d_T = new ArrayList<>();
		ArrayList<ArcIn> d_In = new ArrayList<>();
		ArrayList<ArcOut> d_Out = new ArrayList<>();
		d_P.add(new PetriP("P1",1));
		d_P.add(new PetriP("P2",0));
		d_P.add(new PetriP("P3",0));
		d_P.add(new PetriP("P4",0));
		d_P.add(new PetriP("P5",0));
		d_P.add(new PetriP("Черга на обслуговування",0));
		d_P.add(new PetriP("Оператори",operators));
		d_P.add(new PetriP("P8",0));
		d_P.add(new PetriP("P9",0));
		d_P.add(new PetriP("P10",0));
		d_P.add(new PetriP("P11",0));
		d_P.add(new PetriP("P12",0));
		d_P.add(new PetriP("P13",0));
		d_P.add(new PetriP("P14",0));
		d_P.add(new PetriP("P15",0));
		d_P.add(new PetriP("P16",0));
		d_P.add(new PetriP("P17",0));
		d_P.add(new PetriP("P18",0));
		d_P.add(new PetriP("Кількість абонентів, що припинила набір",0));
		d_P.add(new PetriP("P20",0));
		d_P.add(new PetriP("Водії таксі",drivers));
		d_P.add(new PetriP("Кількість клієнтів, які скористалися послугами таксі",0));
		d_T.add(new PetriT("Надходження викликів",meanCallArrival));
		d_T.get(0).setDistribution("erl", d_T.get(0).getTimeServ());
		d_T.get(0).setParamDeviation(2.0);
		d_T.add(new PetriT("Набирання номера",meanPhoneNumberDialing));
		d_T.add(new PetriT("Спроба замовлення таксі",meanTaxiOrdering));
		d_T.get(2).setDistribution("exp", d_T.get(2).getTimeServ());
		d_T.get(2).setParamDeviation(0.0);
		d_T.get(2).setPriority(1);
		d_T.add(new PetriT("Надходження на обслуговування",0.0));
		d_T.add(new PetriT("Потрібний повторний набір",0.0));
		d_T.add(new PetriT("Потрібне повторне набирання",0.0));
		d_T.get(5).setPriority(1);
		d_T.add(new PetriT("Очікування повторного набирання",meanWaitingForCalling));
		d_T.add(new PetriT("Набирання номера",meanPhoneNumberDialing));
		d_T.add(new PetriT("Спроба замовлення таксі",meanTaxiOrdering));
		d_T.get(8).setDistribution("exp", d_T.get(8).getTimeServ());
		d_T.get(8).setParamDeviation(0.0);
		d_T.get(8).setPriority(1);
		d_T.add(new PetriT("Надходження на обслуговування",0.0));
		d_T.add(new PetriT("Потрібний повторний набір",0.0));
		d_T.add(new PetriT("Потрібне повторне набирання",0.0));
		d_T.get(11).setPriority(1);
		d_T.add(new PetriT("Очікування повторного набирання",meanWaitingForCalling));
		d_T.add(new PetriT("Набирання номера",meanPhoneNumberDialing));
		d_T.add(new PetriT("Спроба замовлення таксі",meanTaxiOrdering));
		d_T.get(14).setDistribution("exp", d_T.get(14).getTimeServ());
		d_T.get(14).setParamDeviation(0.0);
		d_T.get(14).setPriority(1);
		d_T.add(new PetriT("Надходження на обслуговування",0.0));
		d_T.add(new PetriT("Потрібен повторний набір",0.0));
		d_T.add(new PetriT("Потрібне повторне набирання",0.0));
		d_T.get(17).setPriority(1);
		d_T.add(new PetriT("Очікування повторного набирання",meanWaitingForCalling));
		d_T.add(new PetriT("Набирання номера",meanPhoneNumberDialing));
		d_T.add(new PetriT("Спроба замовлення таксі",meanTaxiOrdering));
		d_T.get(20).setDistribution("exp", d_T.get(20).getTimeServ());
		d_T.get(20).setParamDeviation(0.0);
		d_T.get(20).setPriority(1);
		d_T.add(new PetriT("Надходження на обслуговування",0.0));
		d_T.add(new PetriT("Абонент припиняє набір",0.0));
		d_T.add(new PetriT("Абонент припиняє набирання",0.0));
		d_T.get(23).setPriority(1);
		d_T.add(new PetriT("Проїзд до клієнта",35.0));
		d_T.get(24).setDistribution("emp+unif", d_T.get(24).getTimeServ());
		d_T.get(24).setParamDeviation(5.0);
		d_T.get(24).setValues(distances);
		d_T.get(24).setProbabilities(distanceProbabilities);
		d_T.add(new PetriT("Обслуговування клієнта",meanServing));
		d_T.get(25).setDistribution("unif", d_T.get(25).getTimeServ());
		d_T.get(25).setParamDeviation(10.0);
		d_In.add(new ArcIn(d_P.get(10),d_T.get(12),1));
		d_In.add(new ArcIn(d_P.get(19),d_T.get(25),1));
		d_In.add(new ArcIn(d_P.get(16),d_T.get(22),1));
		d_In.add(new ArcIn(d_P.get(1),d_T.get(1),1));
		d_In.add(new ArcIn(d_P.get(17),d_T.get(21),1));
		d_In.add(new ArcIn(d_P.get(5),d_T.get(24),1));
		d_In.add(new ArcIn(d_P.get(20),d_T.get(24),1));
		d_In.add(new ArcIn(d_P.get(0),d_T.get(0),1));
		d_In.add(new ArcIn(d_P.get(12),d_T.get(16),1));
		d_In.add(new ArcIn(d_P.get(3),d_T.get(3),1));
		d_In.add(new ArcIn(d_P.get(2),d_T.get(4),1));
		d_In.add(new ArcIn(d_P.get(8),d_T.get(8),1));
		d_In.add(new ArcIn(d_P.get(6),d_T.get(8),1));
		d_In.add(new ArcIn(d_P.get(13),d_T.get(15),1));
		d_In.add(new ArcIn(d_P.get(16),d_T.get(20),1));
		d_In.add(new ArcIn(d_P.get(6),d_T.get(20),1));
		d_In.add(new ArcIn(d_P.get(7),d_T.get(7),1));
		d_In.add(new ArcIn(d_P.get(12),d_T.get(14),1));
		d_In.add(new ArcIn(d_P.get(6),d_T.get(14),1));
		d_In.add(new ArcIn(d_P.get(2),d_T.get(2),1));
		d_In.add(new ArcIn(d_P.get(6),d_T.get(2),1));
		d_In.add(new ArcIn(d_P.get(11),d_T.get(13),1));
		d_In.add(new ArcIn(d_P.get(17),d_T.get(23),1));
		d_In.add(new ArcIn(d_P.get(5),d_T.get(23),10));
		d_In.get(23).setInf(true);
		d_In.add(new ArcIn(d_P.get(9),d_T.get(11),1));
		d_In.add(new ArcIn(d_P.get(5),d_T.get(11),10));
		d_In.get(25).setInf(true);
		d_In.add(new ArcIn(d_P.get(3),d_T.get(5),1));
		d_In.add(new ArcIn(d_P.get(5),d_T.get(5),10));
		d_In.get(27).setInf(true);
		d_In.add(new ArcIn(d_P.get(13),d_T.get(17),1));
		d_In.add(new ArcIn(d_P.get(5),d_T.get(17),10));
		d_In.get(29).setInf(true);
		d_In.add(new ArcIn(d_P.get(4),d_T.get(6),1));
		d_In.add(new ArcIn(d_P.get(9),d_T.get(9),1));
		d_In.add(new ArcIn(d_P.get(8),d_T.get(10),1));
		d_In.add(new ArcIn(d_P.get(15),d_T.get(19),1));
		d_In.add(new ArcIn(d_P.get(14),d_T.get(18),1));
		d_Out.add(new ArcOut(d_T.get(12),d_P.get(11),1));
		d_Out.add(new ArcOut(d_T.get(25),d_P.get(20),1));
		d_Out.add(new ArcOut(d_T.get(25),d_P.get(21),1));
		d_Out.add(new ArcOut(d_T.get(22),d_P.get(18),1));
		d_Out.add(new ArcOut(d_T.get(1),d_P.get(2),1));
		d_Out.add(new ArcOut(d_T.get(21),d_P.get(5),1));
		d_Out.add(new ArcOut(d_T.get(24),d_P.get(19),1));
		d_Out.add(new ArcOut(d_T.get(0),d_P.get(0),1));
		d_Out.add(new ArcOut(d_T.get(0),d_P.get(1),1));
		d_Out.add(new ArcOut(d_T.get(16),d_P.get(14),1));
		d_Out.add(new ArcOut(d_T.get(3),d_P.get(5),1));
		d_Out.add(new ArcOut(d_T.get(4),d_P.get(4),1));
		d_Out.add(new ArcOut(d_T.get(8),d_P.get(9),1));
		d_Out.add(new ArcOut(d_T.get(8),d_P.get(6),1));
		d_Out.add(new ArcOut(d_T.get(15),d_P.get(5),1));
		d_Out.add(new ArcOut(d_T.get(20),d_P.get(17),1));
		d_Out.add(new ArcOut(d_T.get(20),d_P.get(6),1));
		d_Out.add(new ArcOut(d_T.get(7),d_P.get(8),1));
		d_Out.add(new ArcOut(d_T.get(14),d_P.get(13),1));
		d_Out.add(new ArcOut(d_T.get(14),d_P.get(6),1));
		d_Out.add(new ArcOut(d_T.get(2),d_P.get(3),1));
		d_Out.add(new ArcOut(d_T.get(2),d_P.get(6),1));
		d_Out.add(new ArcOut(d_T.get(13),d_P.get(12),1));
		d_Out.add(new ArcOut(d_T.get(23),d_P.get(18),1));
		d_Out.add(new ArcOut(d_T.get(11),d_P.get(10),1));
		d_Out.add(new ArcOut(d_T.get(5),d_P.get(4),1));
		d_Out.add(new ArcOut(d_T.get(17),d_P.get(14),1));
		d_Out.add(new ArcOut(d_T.get(6),d_P.get(7),1));
		d_Out.add(new ArcOut(d_T.get(9),d_P.get(5),1));
		d_Out.add(new ArcOut(d_T.get(10),d_P.get(10),1));
		d_Out.add(new ArcOut(d_T.get(19),d_P.get(16),1));
		d_Out.add(new ArcOut(d_T.get(18),d_P.get(15),1));
		PetriNet d_Net = new PetriNet("model",d_P,d_T,d_In,d_Out);
		PetriP.initNext();
		PetriT.initNext();
		ArcIn.initNext();
		ArcOut.initNext();

		return d_Net;
	}
}